name: Deploy Preview

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to Vercel Preview
      if: ${{ secrets.VERCEL_TOKEN != '' }}
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./
        scope: ${{ secrets.VERCEL_ORG_ID }}
        
    - name: Deployment Status
      run: |
        if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
          echo "⚠️ Vercel deployment skipped - GitHub secrets not configured"
          echo "ℹ️ Vercel native deployment may still work if repository is connected"
        else
          echo "✅ Vercel deployment completed via GitHub Actions"
        fi
